### ISSUE TITLE
Upgrade title page

### ISSUE THREAD

**Issue by sirjust** [sirjust/DarkChess#30]
background image, cursor icons (both pointer and when hovering over button, button images, fade out and in functionality

**Comment by arthur-schevey** [comment]
#### Buttons
* Indicate on mouse over
* Play, Settings, Quit
* Play Initiates Scene Transition
#### Background
* 3D Environment
* Depth of Field
* Blur?
* Static Image?
#### Scene Transition
* Camera Fly?
* Fade to Black
* Fade into new scene from black
#### Settings
* Full Screen
* Post Processing on or off
* Quality

Quick overview for when I get to work tomorrow
